spring:
  application:
    name: ms-visitors
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/db_visitors_dev?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&defaultAuthenticationPlugin=mysql_native_password
    username: root
    password: mysqlmac
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop  # Recrea las tablas en cada inicio (solo para desarrollo)
    properties:
      hibernate:
        format_sql: true

server:
  port: 9001

jwt:
  secret: ynnZnUmVsXjHBgtOZQuRCiIMeQHPfqXwePYXwiYLIgwsBlvjZe
  expiration: 86400000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    com.cibertec: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
