spring:
  application:
    name: ms-visitors
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/db_visitors?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:mysqlmac}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate  # Solo valida, no modifica la base de datos
    properties:
      hibernate:
        format_sql: false

server:
  port: 9001

jwt:
  secret: ${JWT_SECRET:ynnZnUmVsXjHBgtOZQuRCiIMeQHPfqXwePYXwiYLIgwsBlvjZe}
  expiration: ${JWT_EXPIRATION:86400000}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

logging:
  level:
    com.cibertec: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
