spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ms-users
              uri: lb://ms-users
              predicates:
                - Path=/api/auth/**
            - id: ms-vehiculo
              uri: lb://ms-vehiculo
              predicates:
                - Path=/api/vehiculo/**
            - id: ms-envio
              uri: lb://ms-envio
              predicates:
                - Path=/api/envio/**
              default-filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  service-url:
    defaultZone: http://localhost:8777/eureka
  instance:
    prefer-ip-address: true
