server:
  port: 8090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      # Configuración de rutas
      routes:
        # Ruta para autenticación (ms-users contiene AuthController)
        - id: ms-auth
          uri: http://localhost:9000
          predicates:
            - Path=/api/auth/**
        
        # Ruta para gestión de usuarios (ms-users contiene UserController)
        - id: ms-users
          uri: http://localhost:9000
          predicates:
            - Path=/api/users/**

# Configuración de Eureka (deshabilitado)
eureka:
  client:
    enabled: false

# Configuración de Actuator para monitoreo
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

# Configuración de logging
logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.web.reactive: INFO
    reactor.netty: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"