spring:
  application:
    name: ms-visitantes
  datasource:
    url: jdbc:mysql://localhost:3306/db_visitantes?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&defaultAuthenticationPlugin=mysql_native_password
    username: root
    password: mysqlmac
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 4041

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
